### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by deeplook** [thoth-station/thoth-pybench#15]
I wonder because after installing it with `python setup.py install` I'm getting this:

```
$ pybench --help
------------------------------------------------------------------------
PYBENCH - a benchmark test suite for Python interpreters/compilers.
------------------------------------------------------------------------

Synopsis:
 pybench [option] files...

Options and default settings:

* Internal Error (use --debug to display the traceback)
```

I also get the last line with an otherwise apparently successful run:

```
$ pybench -f p21.pybench
[...]
* Internal Error (use --debug to display the traceback)
```

**Comment by goern** [comment]
/king bug
/priority important-soon

We'll have a look, but it might take a week. Can you help with debugging it a little more? Any logs?

**Comment by fridex** [comment]
I can see this error when the package is installed from PyPI and run with `pybench --help`:

```
Traceback (most recent call last):
  File "/home/fpokorny/git/thoth-station/thoth-pybench/venv/lib64/python3.7/site-packages/pybench/CommandLine.py", line 343, in __init__
    rc = self.parse()
  File "/home/fpokorny/git/thoth-station/thoth-pybench/venv/lib64/python3.7/site-packages/pybench/CommandLine.py", line 464, in parse
    rc = handler(value)
  File "/home/fpokorny/git/thoth-station/thoth-pybench/venv/lib64/python3.7/site-packages/pybench/CommandLine.py", line 568, in handle__help
    self.help()
  File "/home/fpokorny/git/thoth-station/thoth-pybench/venv/lib64/python3.7/site-packages/pybench/CommandLine.py", line 498, in help
    self.print_options()
  File "/home/fpokorny/git/thoth-station/thoth-pybench/venv/lib64/python3.7/site-packages/pybench/CommandLine.py", line 534, in print_options
    items = short + int
TypeError: can only concatenate list (not "type") to list
  <class 'TypeError'>: can only concatenate list (not "type") to list
```

The code is old and was probably not properly ported to Python 3.

I found multiple issues in sources, but I'm not that familiar with them. Will open few PRs to address issues.

Thanks for the report!

**Comment by fridex** [comment]
@deeplook Could you try with the most recent master? These command should work:

```
$ python3 -m venv venv    
$ source venv/bin/activate
(venv) $ pip install git+https://github.com/thoth-station/thoth-pybench
(venv) $ pybench --help
(venv) $ pybench -f p21.pybench    
```

**Comment by fridex** [comment]
I will close this. Feel free to reopen if the issue persists. Thanks for the report, @deeplook!

**Comment by deeplook** [comment]
Thanks!
